[window]
  dimensions.columns = 80
  dimensions.lines = 25
  opacity = 0.65
  blur = false

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]

[font]
  size = 16.0

[font.normal]
  family = 'Mononoki Nerd Font'
  style = "Bold"

[colors]
  primary.background = '0x1F2A28'
  primary.foreground = '0xE5E9F0'

  # Normal colors
  normal.black = '0x000000'
  normal.red = '0xFF5555'
  normal.green = '0x50FA7B'
  normal.yellow = '0xF1FA8C'
  normal.blue = '0xBD93F9'
  normal.magenta = '0xFF79C6'
  normal.cyan = '0x8BE9FD'
  normal.white = '0xBFBFBF'

  # Bright colors
  bright.black = '0x4D4D4D'
  bright.red = '0xFF6E67'
  bright.green = '0x5AF78E'
  bright.yellow = '0xF4F99D'
  bright.blue = '0xCAA9FA'
  bright.magenta = '0xFF92D0'
  bright.cyan = '0x9AEDFE'
  bright.white = '0xE6E6E6'

